project_id = "rsmppgcxrdywybxorvla"

[functions.matching-engine]
verify_jwt = true

[functions.generate-post-content]
verify_jwt = false

[functions.campaign-api]
verify_jwt = false

[functions.payment-gateway]
verify_jwt = false

[functions.admin-api]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.agora-token]
verify_jwt = false

[functions.volunteer-matching]
verify_jwt = false

[functions.content-moderation]
verify_jwt = true

[functions.angel-ai]
verify_jwt = false
